export const defaultData = [
  {
    id: "parent_1",
    name: "New Inquiry",
    total_price: 3200,
    total_leads: 2,
    children: [
      {
        id: 1,
        company_name: "Tiger Nixon",
        mobile: "9865326598",
        compony: "Edinburgh",
      },
      {
        id: 2,
        company_name: "Garrett Winters",
        mobile: "9865326598",
        compony: "Tokyo",
      },
      {
        id: 3,
        company_name: "Ashton Cox",
        mobile: "9865326598",
        compony: "San Francisco",
      },
      {
        id: 4,
        company_name: "Airi Satou",
        mobile: "9865326598",
        compony: "Tokyo",
      },
      {
        id: 5,
        company_name: "Brielle Williamson",
        mobile: "9865326598",
        compony: "New York",
      },
    ],
  },
  {
    id: "parent_2",
    name: "Hot Lead",
    total_price: 4500,
    total_leads: 3,
    children: [
      {
        id: 6,
        company_name: "Herrod Chandler",
        mobile: "9865326598",
        compony: "San Francisco",
      },
      {
        id: 7,
        company_name: "Rhona Davidson",
        mobile: "9865326598",
        compony: "Tokyo",
      },
      {
        id: 8,
        company_name: "Colleen Hurst",
        mobile: "9865326598",
        compony: "San Francisco",
      },
    ],
  },
  {
    id: "parent_3",
    name: "Cold Lead",
    total_price: 2000,
    total_leads: 2,
    children: [
      {
        id: 9,
        company_name: "Sonya Frost",
        mobile: "9865326598",
        compony: "Edinburgh",
      },
      {
        id: 10,
        company_name: "Jena Gaines",
        mobile: "9865326598",
        compony: "London",
      },
    ],
  },
  {
    id: "parent_4",
    name: "Proposal Sent",
    total_price: 3800,
    total_leads: 3,
    children: [
      {
        id: 11,
        company_name: "Quinn Flynn",
        mobile: "9865326598",
        compony: "Edinburgh",
      },
      {
        id: 12,
        company_name: "Charde Marshall",
        mobile: "9865326598",
        compony: "San Francisco",
      },
      {
        id: 13,
        company_name: "Haley Kennedy",
        mobile: "9865326598",
        compony: "London",
      },
    ],
  },
  {
    id: "parent_5",
    name: "Negotiation",
    total_price: 5000,
    total_leads: 4,
    children: [
      {
        id: 14,
        company_name: "Tatyana Fitzpatrick",
        mobile: "9865326598",
        compony: "London",
      },
      {
        id: 15,
        company_name: "Michael Silva",
        mobile: "9865326598",
        compony: "London",
      },
      {
        id: 16,
        company_name: "Paul Byrd",
        mobile: "9865326598",
        compony: "New York",
      },
      {
        id: 17,
        company_name: "Gloria Little",
        mobile: "9865326598",
        compony: "New York",
      },
    ],
  },
  {
    id: "parent_6",
    name: "Won",
    total_price: 6000,
    total_leads: 5,
    children: [
      {
        id: 18,
        company_name: "Bradley Greer",
        mobile: "9865326598",
        compony: "London",
      },
      {
        id: 19,
        company_name: "Dai Rios",
        mobile: "9865326598",
        compony: "Edinburgh",
      },
      {
        id: 20,
        company_name: "Jenette Caldwell",
        mobile: "9865326598",
        compony: "New York",
      },
      {
        id: 21,
        company_name: "Yuri Berry",
        mobile: "9865326598",
        compony: "New York",
      },
      {
        id: 22,
        company_name: "Caesar Vance",
        mobile: "9865326598",
        compony: "New York",
      },
    ],
  },
  {
    id: "parent_7",
    name: "Lost",
    total_price: 7000,
    total_leads: 6,
    children: [
      {
        id: 23,
        company_name: "Doris Greene",
        mobile: "9865326598",
        compony: "New York",
      },
      {
        id: 24,
        company_name: "Angelica Ramos",
        mobile: "9865326598",
        compony: "London",
      },
      {
        id: 25,
        company_name: "Gavin Joyce",
        mobile: "9865326598",
        compony: "Edinburgh",
      },
      {
        id: 26,
        company_name: "Fiona Green",
        mobile: "9865326598",
        compony: "San Francisco",
      },
      {
        id: 27,
        company_name: "Shou Itou",
        mobile: "9865326598",
        compony: "Tokyo",
      },
      {
        id: 28,
        company_name: "Michelle House",
        mobile: "9865326598",
        compony: "Sidney",
      },
    ],
  },
];
